---
# roles/tailscale_manage/tasks/main.yaml

- name: Gather facts if needed
  ansible.builtin.setup:
  when: ansible_os_family is not defined

- name: Display set ansible_host values
  when: ansible_host is defined
  debug:
    msg: "{{ inventory_hostname  }}"

- name: Display set ansible_host values
  when: ansible_host is defined
  debug:
    msg: "{{ ludus | selectattr('vm_name', 'equalto', inventory_hostname ) }}"

- name: Set ansible_host for each VM
  ansible.builtin.set_fact:
    ansible_host: >-
      10.{{ range_second_octet }}.{{
      (ludus | selectattr('vm_name', 'equalto', inventory_hostname) | first).vlan }}.{{
      (ludus | selectattr('vm_name', 'equalto', inventory_hostname) | first).ip_last_octet }}

- name: Display set ansible_host values
  when: ansible_host is defined
  debug:
    msg: "{{ inventory_hostname }}: ansible_host = {{ ansible_host }}"
    
- name: Include install tasks
  ansible.builtin.include_tasks: install.yaml
  when: tailscale_state | default('present') == 'present'

- name: Include uninstall tasks
  ansible.builtin.include_tasks: uninstall.yaml
  when: tailscale_state | default('present') == 'absent'
